<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'vich_uploader.metadata_driver.yaml' shared service.

include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/DriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AbstractFileDriver.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Metadata/Driver/YamlDriver.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AdvancedFileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/FileLocator.php';

return $this->privates['vich_uploader.metadata_driver.yaml'] = new \Vich\UploaderBundle\Metadata\Driver\YamlDriver(($this->privates['vich_uploader.metadata.file_locator'] ?? ($this->privates['vich_uploader.metadata.file_locator'] = new \Metadata\Driver\FileLocator([]))));
