<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'vich_uploader.metadata_factory' shared service.

include_once $this->targetDirs[3].'/vendor/jms/metadata/src/MetadataFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/AdvancedMetadataFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/MetadataFactory.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Cache/CacheInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Cache/FileCache.php';

$this->privates['vich_uploader.metadata_factory'] = $instance = new \Metadata\MetadataFactory(($this->privates['vich_uploader.metadata_driver.chain'] ?? $this->load('getVichUploader_MetadataDriver_ChainService.php')), 'Metadata\\ClassHierarchyMetadata', true);

$instance->setCache(($this->privates['vich_uploader.metadata.cache.file_cache'] ?? ($this->privates['vich_uploader.metadata.cache.file_cache'] = new \Metadata\Cache\FileCache(($this->targetDirs[0].'/vich_uploader')))));

return $instance;
