vich_uploader:
    db_driver: orm

    mappings:
       User:
           uri_prefix: /assets/img
           upload_destination: '%kernel.project_dir%/../filrouge/src/assets/img'
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true