vich_uploader:
    db_driver: orm

    mappings:
       User:
           uri_prefix: /images/User
           upload_destination: '%kernel.project_dir%/public/images/User'
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true