<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'vich_uploader.metadata_driver.chain' shared service.

include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/DriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/DriverChain.php';

return $this->privates['vich_uploader.metadata_driver.chain'] = new \Metadata\Driver\DriverChain([0 => ($this->privates['vich_uploader.metadata_driver.xml'] ?? $this->load('getVichUploader_MetadataDriver_XmlService.php')), 1 => ($this->privates['vich_uploader.metadata_driver.annotation'] ?? $this->load('getVichUploader_MetadataDriver_AnnotationService.php')), 2 => ($this->privates['vich_uploader.metadata_driver.yaml'] ?? $this->load('getVichUploader_MetadataDriver_YamlService.php'))]);
