<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'vich_uploader.property_mapping_factory' shared service.

include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Mapping/PropertyMappingFactory.php';

return $this->privates['vich_uploader.property_mapping_factory'] = new \Vich\UploaderBundle\Mapping\PropertyMappingFactory($this, ($this->privates['vich_uploader.metadata_reader'] ?? $this->load('getVichUploader_MetadataReaderService.php')), $this->getParameter('vich_uploader.mappings'), '_name');
