<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vYGYf0h' shared service.

return $this->privates['.service_locator.vYGYf0h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'profileRepository' => ['privates', 'App\\Repository\\ProfileRepository', 'getProfileRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService.php', true],
], [
    'profileRepository' => 'App\\Repository\\ProfileRepository',
    'serializer' => '?',
]);
