<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'vich_uploader.metadata_reader' shared service.

include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Metadata/MetadataReader.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/MetadataFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/AdvancedMetadataFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/MetadataFactory.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/DriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/DriverChain.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AbstractFileDriver.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Metadata/Driver/XmlDriver.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/AdvancedFileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Driver/FileLocator.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Metadata/Driver/AnnotationDriver.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Metadata/Driver/YamlDriver.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Cache/CacheInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/metadata/src/Cache/FileCache.php';

$a = new \Metadata\Driver\FileLocator([]);

$b = new \Metadata\MetadataFactory(new \Metadata\Driver\DriverChain([0 => new \Vich\UploaderBundle\Metadata\Driver\XmlDriver($a), 1 => new \Vich\UploaderBundle\Metadata\Driver\AnnotationDriver(($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService())), 2 => new \Vich\UploaderBundle\Metadata\Driver\YamlDriver($a)]), 'Metadata\\ClassHierarchyMetadata', true);
$b->setCache(new \Metadata\Cache\FileCache(($this->targetDirs[0].'/vich_uploader')));

return $this->privates['vich_uploader.metadata_reader'] = new \Vich\UploaderBundle\Metadata\MetadataReader($b);
