<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.templating.helper.uploader_helper' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Templating/Helper/UploaderHelper.php';

return $this->services['vich_uploader.templating.helper.uploader_helper'] = new \Vich\UploaderBundle\Templating\Helper\UploaderHelper(($this->privates['vich_uploader.storage.file_system'] ?? $this->load('getVichUploader_Storage_FileSystemService.php')));
