<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGXKxMQw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGXKxMQw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGXKxMQw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGXKxMQw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGXKxMQw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GXKxMQw',
    'container.build_id' => 'c9fe81cb',
    'container.build_time' => 1565020913,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGXKxMQw');
