<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQVWyda\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQVWyda/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXQVWyda.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXQVWyda\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXQVWyda\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XQVWyda',
    'container.build_id' => '648833d8',
    'container.build_time' => 1572135189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQVWyda');
