<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'partenaire' => [[], ['_controller' => 'App\\Controller\\PartenaireController::index'], [], [['text', '/api/partenaire']], [], []],
    'liste' => [[], ['_controller' => 'App\\Controller\\PartenaireController::show'], [], [['text', '/api/liste']], [], []],
    'histor' => [[], ['_controller' => 'App\\Controller\\PartenaireController::historique'], [], [['text', '/api/history']], [], []],
    'add' => [[], ['_controller' => 'App\\Controller\\PartenaireController::ajoutP'], [], [['text', '/api/addP']], [], []],
    'par' => [['id'], ['_controller' => 'App\\Controller\\PartenaireController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/bloquer']], [], []],
    'upda' => [[], ['_controller' => 'App\\Controller\\PartenaireController::depot'], [], [['text', '/api/depot']], [], []],
    'compte' => [[], ['_controller' => 'App\\Controller\\PartenaireController::addCompte'], [], [['text', '/api/addCompte']], [], []],
    'security' => [[], ['_controller' => 'App\\Controller\\SecurityController::acceuil'], [], [['text', '/api/admin']], [], []],
    'list' => [[], ['_controller' => 'App\\Controller\\SecurityController::index'], [], [['text', '/api/liste']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/api/register']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/api/login']], [], []],
    'user' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/etat']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
